---

- name: "Check mounts"
  hosts: all
  vars: 
    df_threshold: 10

  tasks:
    - debug:
        msg: "{{ ansible_mounts }}"

    - name: check mounts
      ansible.builtin.shell: >
        df -h |
        tail -n +2 |
        sed s/%//g |
        awk '{ if($5 > {{ df_threshold | int }}) print "Alert "$0;}'
      register: result
      changed_when: False
      failed_when: result.rc != 0