---

- name: "Check mounts"
  hosts: all

  tasks:
    - debug:
        msg: "{{ ansible_mounts }}"

    - name: check mounts
      ansible.builtin.shell: >
        df -h |
        tail -n +2 |
        sed s/%//g |
        awk '{ if($5 > 90) print "Alert "$0;}'
      changed_when: False
      failed_when: result.rc != 0