---

- name: "Check mounts"
  hosts: all

  tasks:
    - debug:
        msg: "{{ ansible_mounts }}"

    - debug:
        msg: "{{ item.mount }}"
      with_items: "{{ ansible_mounts }}"

    - name: check mounts
      ansible.builtin.shell: >
        df -h |
        tail -n +2 |
        sed s/%//g |
        awk '{ if($5 > 0) print "Alert "$0;}'