---

- name: "Launch RHEL AMI"
  hosts: localhost
  gather_facts: no
    
  roles:
  - launch_ami

  tasks:
  - name: debug
    debug:
      var: ec2.results

  - name: "Wait for connection on all hosts."
    wait_for:
      host: "{{ item['tagged_instances'][0]['private_ip'] }}"
      port: 22
      timeout: 500
    loop: "{{ ec2.results }}"
    loop_control:
      label: "{{ item['tagged_instances'][0]['private_ip'] }}"
