---

- name: "Launch RHEL AMI"
  hosts: localhost
  gather_facts: no
    
  roles:
  - launch_ami

  tasks:
  - name: debug
    debug:
      var: ec2.results[0]

  - name: "Wait for connection on all hosts."
    wait_for:
      host: "{{ item['private_dns_name'] }}"
      port: 22
      timeout: 500
    loop: "{{ ec2.results[0].instances }}"
    loop_control:
      label: "{{ item['private_dns_name'] }}"
    when: ec2.results[0].instances